LOCAL_PATH := $(call my-dir)

# AndroidSystemIntelligence
include $(CLEAR_VARS)
LOCAL_MODULE := AndroidSystemIntelligence
LOCAL_SRC_FILES := $(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_SYSTEM_EXT_MODULE := true
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_OVERRIDES_PACKAGES := SettingsIntelligence
include $(BUILD_PREBUILT)
